# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wandr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wandr
    pod 'SnapKit'
    pod 'TwicketSegmentedControl’, :git => 'https://github.com/anama118118/TwicketSegmentedControl.git'
end
